package models

import (
	"fmt"
	"time"

	"github.com/jinzhu/gorm"
)

// ===== BEGIN of all query sets

// ===== BEGIN of query set AutotransferQuerySet

// AutotransferQuerySet is an queryset type for Autotransfer
type AutotransferQuerySet struct {
	db *gorm.DB
}

// NewAutotransferQuerySet constructs new AutotransferQuerySet
func NewAutotransferQuerySet(db *gorm.DB) AutotransferQuerySet {
	return AutotransferQuerySet{
		db: db.Model(&Autotransfer{}),
	}
}

func (qs AutotransferQuerySet) w(db *gorm.DB) AutotransferQuerySet {
	return NewAutotransferQuerySet(db)
}

// All is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) All(ret *[]Autotransfer) error {
	return qs.db.Find(ret).Error
}

// AmountEq is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) AmountEq(amount uint) AutotransferQuerySet {
	return qs.w(qs.db.Where("amount = ?", amount))
}

// AmountGt is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) AmountGt(amount uint) AutotransferQuerySet {
	return qs.w(qs.db.Where("amount > ?", amount))
}

// AmountGte is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) AmountGte(amount uint) AutotransferQuerySet {
	return qs.w(qs.db.Where("amount >= ?", amount))
}

// AmountIn is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) AmountIn(amount uint, amountRest ...uint) AutotransferQuerySet {
	iArgs := []interface{}{amount}
	for _, arg := range amountRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("amount IN (?)", iArgs))
}

// AmountLt is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) AmountLt(amount uint) AutotransferQuerySet {
	return qs.w(qs.db.Where("amount < ?", amount))
}

// AmountLte is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) AmountLte(amount uint) AutotransferQuerySet {
	return qs.w(qs.db.Where("amount <= ?", amount))
}

// AmountNe is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) AmountNe(amount uint) AutotransferQuerySet {
	return qs.w(qs.db.Where("amount != ?", amount))
}

// AmountNotIn is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) AmountNotIn(amount uint, amountRest ...uint) AutotransferQuerySet {
	iArgs := []interface{}{amount}
	for _, arg := range amountRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("amount NOT IN (?)", iArgs))
}

// Count is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) Count() (int, error) {
	var count int
	err := qs.db.Count(&count).Error
	return count, err
}

// Create is an autogenerated method
// nolint: dupl
func (o *Autotransfer) Create(db *gorm.DB) error {
	return db.Create(o).Error
}

// CreatedAtEq is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) CreatedAtEq(createdAt time.Time) AutotransferQuerySet {
	return qs.w(qs.db.Where("created_at = ?", createdAt))
}

// CreatedAtGt is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) CreatedAtGt(createdAt time.Time) AutotransferQuerySet {
	return qs.w(qs.db.Where("created_at > ?", createdAt))
}

// CreatedAtGte is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) CreatedAtGte(createdAt time.Time) AutotransferQuerySet {
	return qs.w(qs.db.Where("created_at >= ?", createdAt))
}

// CreatedAtLt is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) CreatedAtLt(createdAt time.Time) AutotransferQuerySet {
	return qs.w(qs.db.Where("created_at < ?", createdAt))
}

// CreatedAtLte is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) CreatedAtLte(createdAt time.Time) AutotransferQuerySet {
	return qs.w(qs.db.Where("created_at <= ?", createdAt))
}

// CreatedAtNe is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) CreatedAtNe(createdAt time.Time) AutotransferQuerySet {
	return qs.w(qs.db.Where("created_at != ?", createdAt))
}

// Delete is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) Delete() error {
	return qs.db.Delete(Autotransfer{}).Error
}

// Delete is an autogenerated method
// nolint: dupl
func (o *Autotransfer) Delete(db *gorm.DB) error {
	return db.Delete(o).Error
}

// DeletedAtEq is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) DeletedAtEq(deletedAt time.Time) AutotransferQuerySet {
	return qs.w(qs.db.Where("deleted_at = ?", deletedAt))
}

// DeletedAtGt is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) DeletedAtGt(deletedAt time.Time) AutotransferQuerySet {
	return qs.w(qs.db.Where("deleted_at > ?", deletedAt))
}

// DeletedAtGte is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) DeletedAtGte(deletedAt time.Time) AutotransferQuerySet {
	return qs.w(qs.db.Where("deleted_at >= ?", deletedAt))
}

// DeletedAtIsNotNull is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) DeletedAtIsNotNull() AutotransferQuerySet {
	return qs.w(qs.db.Where("deleted_at IS NOT NULL"))
}

// DeletedAtIsNull is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) DeletedAtIsNull() AutotransferQuerySet {
	return qs.w(qs.db.Where("deleted_at IS NULL"))
}

// DeletedAtLt is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) DeletedAtLt(deletedAt time.Time) AutotransferQuerySet {
	return qs.w(qs.db.Where("deleted_at < ?", deletedAt))
}

// DeletedAtLte is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) DeletedAtLte(deletedAt time.Time) AutotransferQuerySet {
	return qs.w(qs.db.Where("deleted_at <= ?", deletedAt))
}

// DeletedAtNe is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) DeletedAtNe(deletedAt time.Time) AutotransferQuerySet {
	return qs.w(qs.db.Where("deleted_at != ?", deletedAt))
}

// GetUpdater is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) GetUpdater() AutotransferUpdater {
	return NewAutotransferUpdater(qs.db)
}

// IDEq is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) IDEq(ID uint) AutotransferQuerySet {
	return qs.w(qs.db.Where("id = ?", ID))
}

// IDGt is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) IDGt(ID uint) AutotransferQuerySet {
	return qs.w(qs.db.Where("id > ?", ID))
}

// IDGte is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) IDGte(ID uint) AutotransferQuerySet {
	return qs.w(qs.db.Where("id >= ?", ID))
}

// IDIn is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) IDIn(ID uint, IDRest ...uint) AutotransferQuerySet {
	iArgs := []interface{}{ID}
	for _, arg := range IDRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("id IN (?)", iArgs))
}

// IDLt is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) IDLt(ID uint) AutotransferQuerySet {
	return qs.w(qs.db.Where("id < ?", ID))
}

// IDLte is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) IDLte(ID uint) AutotransferQuerySet {
	return qs.w(qs.db.Where("id <= ?", ID))
}

// IDNe is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) IDNe(ID uint) AutotransferQuerySet {
	return qs.w(qs.db.Where("id != ?", ID))
}

// IDNotIn is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) IDNotIn(ID uint, IDRest ...uint) AutotransferQuerySet {
	iArgs := []interface{}{ID}
	for _, arg := range IDRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("id NOT IN (?)", iArgs))
}

// Limit is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) Limit(limit int) AutotransferQuerySet {
	return qs.w(qs.db.Limit(limit))
}

// One is used to retrieve one result. It returns gorm.ErrRecordNotFound
// if nothing was fetched
func (qs AutotransferQuerySet) One(ret *Autotransfer) error {
	return qs.db.First(ret).Error
}

// OrderAscByAmount is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) OrderAscByAmount() AutotransferQuerySet {
	return qs.w(qs.db.Order("amount ASC"))
}

// OrderAscByCreatedAt is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) OrderAscByCreatedAt() AutotransferQuerySet {
	return qs.w(qs.db.Order("created_at ASC"))
}

// OrderAscByDeletedAt is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) OrderAscByDeletedAt() AutotransferQuerySet {
	return qs.w(qs.db.Order("deleted_at ASC"))
}

// OrderAscByID is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) OrderAscByID() AutotransferQuerySet {
	return qs.w(qs.db.Order("id ASC"))
}

// OrderAscBySourceID is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) OrderAscBySourceID() AutotransferQuerySet {
	return qs.w(qs.db.Order("source_id ASC"))
}

// OrderAscBySourceTxnID is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) OrderAscBySourceTxnID() AutotransferQuerySet {
	return qs.w(qs.db.Order("source_txn_id ASC"))
}

// OrderAscBySourceType is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) OrderAscBySourceType() AutotransferQuerySet {
	return qs.w(qs.db.Order("source_type ASC"))
}

// OrderAscByTargetTxnID is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) OrderAscByTargetTxnID() AutotransferQuerySet {
	return qs.w(qs.db.Order("target_txn_id ASC"))
}

// OrderAscByTargetType is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) OrderAscByTargetType() AutotransferQuerySet {
	return qs.w(qs.db.Order("target_type ASC"))
}

// OrderAscByUpdatedAt is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) OrderAscByUpdatedAt() AutotransferQuerySet {
	return qs.w(qs.db.Order("updated_at ASC"))
}

// OrderDescByAmount is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) OrderDescByAmount() AutotransferQuerySet {
	return qs.w(qs.db.Order("amount DESC"))
}

// OrderDescByCreatedAt is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) OrderDescByCreatedAt() AutotransferQuerySet {
	return qs.w(qs.db.Order("created_at DESC"))
}

// OrderDescByDeletedAt is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) OrderDescByDeletedAt() AutotransferQuerySet {
	return qs.w(qs.db.Order("deleted_at DESC"))
}

// OrderDescByID is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) OrderDescByID() AutotransferQuerySet {
	return qs.w(qs.db.Order("id DESC"))
}

// OrderDescBySourceID is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) OrderDescBySourceID() AutotransferQuerySet {
	return qs.w(qs.db.Order("source_id DESC"))
}

// OrderDescBySourceTxnID is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) OrderDescBySourceTxnID() AutotransferQuerySet {
	return qs.w(qs.db.Order("source_txn_id DESC"))
}

// OrderDescBySourceType is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) OrderDescBySourceType() AutotransferQuerySet {
	return qs.w(qs.db.Order("source_type DESC"))
}

// OrderDescByTargetTxnID is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) OrderDescByTargetTxnID() AutotransferQuerySet {
	return qs.w(qs.db.Order("target_txn_id DESC"))
}

// OrderDescByTargetType is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) OrderDescByTargetType() AutotransferQuerySet {
	return qs.w(qs.db.Order("target_type DESC"))
}

// OrderDescByUpdatedAt is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) OrderDescByUpdatedAt() AutotransferQuerySet {
	return qs.w(qs.db.Order("updated_at DESC"))
}

// SetAmount is an autogenerated method
// nolint: dupl
func (u AutotransferUpdater) SetAmount(amount uint) AutotransferUpdater {
	u.fields[string(AutotransferDBSchema.Amount)] = amount
	return u
}

// SetCreatedAt is an autogenerated method
// nolint: dupl
func (u AutotransferUpdater) SetCreatedAt(createdAt time.Time) AutotransferUpdater {
	u.fields[string(AutotransferDBSchema.CreatedAt)] = createdAt
	return u
}

// SetDeletedAt is an autogenerated method
// nolint: dupl
func (u AutotransferUpdater) SetDeletedAt(deletedAt *time.Time) AutotransferUpdater {
	u.fields[string(AutotransferDBSchema.DeletedAt)] = deletedAt
	return u
}

// SetID is an autogenerated method
// nolint: dupl
func (u AutotransferUpdater) SetID(ID uint) AutotransferUpdater {
	u.fields[string(AutotransferDBSchema.ID)] = ID
	return u
}

// SetSourceID is an autogenerated method
// nolint: dupl
func (u AutotransferUpdater) SetSourceID(sourceID uint) AutotransferUpdater {
	u.fields[string(AutotransferDBSchema.SourceID)] = sourceID
	return u
}

// SetSourceTxnID is an autogenerated method
// nolint: dupl
func (u AutotransferUpdater) SetSourceTxnID(sourceTxnID uint) AutotransferUpdater {
	u.fields[string(AutotransferDBSchema.SourceTxnID)] = sourceTxnID
	return u
}

// SetSourceType is an autogenerated method
// nolint: dupl
func (u AutotransferUpdater) SetSourceType(sourceType AppLevel) AutotransferUpdater {
	u.fields[string(AutotransferDBSchema.SourceType)] = sourceType
	return u
}

// SetTargetID is an autogenerated method
// nolint: dupl
func (u AutotransferUpdater) SetTargetID(targetID string) AutotransferUpdater {
	u.fields[string(AutotransferDBSchema.TargetID)] = targetID
	return u
}

// SetTargetTxnID is an autogenerated method
// nolint: dupl
func (u AutotransferUpdater) SetTargetTxnID(targetTxnID uint) AutotransferUpdater {
	u.fields[string(AutotransferDBSchema.TargetTxnID)] = targetTxnID
	return u
}

// SetTargetType is an autogenerated method
// nolint: dupl
func (u AutotransferUpdater) SetTargetType(targetType AppLevel) AutotransferUpdater {
	u.fields[string(AutotransferDBSchema.TargetType)] = targetType
	return u
}

// SetUpdatedAt is an autogenerated method
// nolint: dupl
func (u AutotransferUpdater) SetUpdatedAt(updatedAt time.Time) AutotransferUpdater {
	u.fields[string(AutotransferDBSchema.UpdatedAt)] = updatedAt
	return u
}

// SourceIDEq is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) SourceIDEq(sourceID uint) AutotransferQuerySet {
	return qs.w(qs.db.Where("source_id = ?", sourceID))
}

// SourceIDGt is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) SourceIDGt(sourceID uint) AutotransferQuerySet {
	return qs.w(qs.db.Where("source_id > ?", sourceID))
}

// SourceIDGte is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) SourceIDGte(sourceID uint) AutotransferQuerySet {
	return qs.w(qs.db.Where("source_id >= ?", sourceID))
}

// SourceIDIn is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) SourceIDIn(sourceID uint, sourceIDRest ...uint) AutotransferQuerySet {
	iArgs := []interface{}{sourceID}
	for _, arg := range sourceIDRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("source_id IN (?)", iArgs))
}

// SourceIDLt is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) SourceIDLt(sourceID uint) AutotransferQuerySet {
	return qs.w(qs.db.Where("source_id < ?", sourceID))
}

// SourceIDLte is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) SourceIDLte(sourceID uint) AutotransferQuerySet {
	return qs.w(qs.db.Where("source_id <= ?", sourceID))
}

// SourceIDNe is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) SourceIDNe(sourceID uint) AutotransferQuerySet {
	return qs.w(qs.db.Where("source_id != ?", sourceID))
}

// SourceIDNotIn is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) SourceIDNotIn(sourceID uint, sourceIDRest ...uint) AutotransferQuerySet {
	iArgs := []interface{}{sourceID}
	for _, arg := range sourceIDRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("source_id NOT IN (?)", iArgs))
}

// SourceTxnIDEq is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) SourceTxnIDEq(sourceTxnID uint) AutotransferQuerySet {
	return qs.w(qs.db.Where("source_txn_id = ?", sourceTxnID))
}

// SourceTxnIDGt is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) SourceTxnIDGt(sourceTxnID uint) AutotransferQuerySet {
	return qs.w(qs.db.Where("source_txn_id > ?", sourceTxnID))
}

// SourceTxnIDGte is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) SourceTxnIDGte(sourceTxnID uint) AutotransferQuerySet {
	return qs.w(qs.db.Where("source_txn_id >= ?", sourceTxnID))
}

// SourceTxnIDIn is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) SourceTxnIDIn(sourceTxnID uint, sourceTxnIDRest ...uint) AutotransferQuerySet {
	iArgs := []interface{}{sourceTxnID}
	for _, arg := range sourceTxnIDRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("source_txn_id IN (?)", iArgs))
}

// SourceTxnIDLt is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) SourceTxnIDLt(sourceTxnID uint) AutotransferQuerySet {
	return qs.w(qs.db.Where("source_txn_id < ?", sourceTxnID))
}

// SourceTxnIDLte is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) SourceTxnIDLte(sourceTxnID uint) AutotransferQuerySet {
	return qs.w(qs.db.Where("source_txn_id <= ?", sourceTxnID))
}

// SourceTxnIDNe is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) SourceTxnIDNe(sourceTxnID uint) AutotransferQuerySet {
	return qs.w(qs.db.Where("source_txn_id != ?", sourceTxnID))
}

// SourceTxnIDNotIn is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) SourceTxnIDNotIn(sourceTxnID uint, sourceTxnIDRest ...uint) AutotransferQuerySet {
	iArgs := []interface{}{sourceTxnID}
	for _, arg := range sourceTxnIDRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("source_txn_id NOT IN (?)", iArgs))
}

// SourceTypeEq is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) SourceTypeEq(sourceType AppLevel) AutotransferQuerySet {
	return qs.w(qs.db.Where("source_type = ?", sourceType))
}

// SourceTypeGt is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) SourceTypeGt(sourceType AppLevel) AutotransferQuerySet {
	return qs.w(qs.db.Where("source_type > ?", sourceType))
}

// SourceTypeGte is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) SourceTypeGte(sourceType AppLevel) AutotransferQuerySet {
	return qs.w(qs.db.Where("source_type >= ?", sourceType))
}

// SourceTypeIn is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) SourceTypeIn(sourceType AppLevel, sourceTypeRest ...AppLevel) AutotransferQuerySet {
	iArgs := []interface{}{sourceType}
	for _, arg := range sourceTypeRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("source_type IN (?)", iArgs))
}

// SourceTypeLt is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) SourceTypeLt(sourceType AppLevel) AutotransferQuerySet {
	return qs.w(qs.db.Where("source_type < ?", sourceType))
}

// SourceTypeLte is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) SourceTypeLte(sourceType AppLevel) AutotransferQuerySet {
	return qs.w(qs.db.Where("source_type <= ?", sourceType))
}

// SourceTypeNe is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) SourceTypeNe(sourceType AppLevel) AutotransferQuerySet {
	return qs.w(qs.db.Where("source_type != ?", sourceType))
}

// SourceTypeNotIn is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) SourceTypeNotIn(sourceType AppLevel, sourceTypeRest ...AppLevel) AutotransferQuerySet {
	iArgs := []interface{}{sourceType}
	for _, arg := range sourceTypeRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("source_type NOT IN (?)", iArgs))
}

// TargetIDEq is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) TargetIDEq(targetID string) AutotransferQuerySet {
	return qs.w(qs.db.Where("target_id = ?", targetID))
}

// TargetIDIn is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) TargetIDIn(targetID string, targetIDRest ...string) AutotransferQuerySet {
	iArgs := []interface{}{targetID}
	for _, arg := range targetIDRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("target_id IN (?)", iArgs))
}

// TargetIDNe is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) TargetIDNe(targetID string) AutotransferQuerySet {
	return qs.w(qs.db.Where("target_id != ?", targetID))
}

// TargetIDNotIn is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) TargetIDNotIn(targetID string, targetIDRest ...string) AutotransferQuerySet {
	iArgs := []interface{}{targetID}
	for _, arg := range targetIDRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("target_id NOT IN (?)", iArgs))
}

// TargetTxnIDEq is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) TargetTxnIDEq(targetTxnID uint) AutotransferQuerySet {
	return qs.w(qs.db.Where("target_txn_id = ?", targetTxnID))
}

// TargetTxnIDGt is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) TargetTxnIDGt(targetTxnID uint) AutotransferQuerySet {
	return qs.w(qs.db.Where("target_txn_id > ?", targetTxnID))
}

// TargetTxnIDGte is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) TargetTxnIDGte(targetTxnID uint) AutotransferQuerySet {
	return qs.w(qs.db.Where("target_txn_id >= ?", targetTxnID))
}

// TargetTxnIDIn is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) TargetTxnIDIn(targetTxnID uint, targetTxnIDRest ...uint) AutotransferQuerySet {
	iArgs := []interface{}{targetTxnID}
	for _, arg := range targetTxnIDRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("target_txn_id IN (?)", iArgs))
}

// TargetTxnIDLt is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) TargetTxnIDLt(targetTxnID uint) AutotransferQuerySet {
	return qs.w(qs.db.Where("target_txn_id < ?", targetTxnID))
}

// TargetTxnIDLte is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) TargetTxnIDLte(targetTxnID uint) AutotransferQuerySet {
	return qs.w(qs.db.Where("target_txn_id <= ?", targetTxnID))
}

// TargetTxnIDNe is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) TargetTxnIDNe(targetTxnID uint) AutotransferQuerySet {
	return qs.w(qs.db.Where("target_txn_id != ?", targetTxnID))
}

// TargetTxnIDNotIn is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) TargetTxnIDNotIn(targetTxnID uint, targetTxnIDRest ...uint) AutotransferQuerySet {
	iArgs := []interface{}{targetTxnID}
	for _, arg := range targetTxnIDRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("target_txn_id NOT IN (?)", iArgs))
}

// TargetTypeEq is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) TargetTypeEq(targetType AppLevel) AutotransferQuerySet {
	return qs.w(qs.db.Where("target_type = ?", targetType))
}

// TargetTypeGt is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) TargetTypeGt(targetType AppLevel) AutotransferQuerySet {
	return qs.w(qs.db.Where("target_type > ?", targetType))
}

// TargetTypeGte is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) TargetTypeGte(targetType AppLevel) AutotransferQuerySet {
	return qs.w(qs.db.Where("target_type >= ?", targetType))
}

// TargetTypeIn is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) TargetTypeIn(targetType AppLevel, targetTypeRest ...AppLevel) AutotransferQuerySet {
	iArgs := []interface{}{targetType}
	for _, arg := range targetTypeRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("target_type IN (?)", iArgs))
}

// TargetTypeLt is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) TargetTypeLt(targetType AppLevel) AutotransferQuerySet {
	return qs.w(qs.db.Where("target_type < ?", targetType))
}

// TargetTypeLte is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) TargetTypeLte(targetType AppLevel) AutotransferQuerySet {
	return qs.w(qs.db.Where("target_type <= ?", targetType))
}

// TargetTypeNe is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) TargetTypeNe(targetType AppLevel) AutotransferQuerySet {
	return qs.w(qs.db.Where("target_type != ?", targetType))
}

// TargetTypeNotIn is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) TargetTypeNotIn(targetType AppLevel, targetTypeRest ...AppLevel) AutotransferQuerySet {
	iArgs := []interface{}{targetType}
	for _, arg := range targetTypeRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("target_type NOT IN (?)", iArgs))
}

// Update is an autogenerated method
// nolint: dupl
func (u AutotransferUpdater) Update() error {
	return u.db.Updates(u.fields).Error
}

// UpdateNum is an autogenerated method
// nolint: dupl
func (u AutotransferUpdater) UpdateNum() (int64, error) {
	db := u.db.Updates(u.fields)
	return db.RowsAffected, db.Error
}

// UpdatedAtEq is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) UpdatedAtEq(updatedAt time.Time) AutotransferQuerySet {
	return qs.w(qs.db.Where("updated_at = ?", updatedAt))
}

// UpdatedAtGt is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) UpdatedAtGt(updatedAt time.Time) AutotransferQuerySet {
	return qs.w(qs.db.Where("updated_at > ?", updatedAt))
}

// UpdatedAtGte is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) UpdatedAtGte(updatedAt time.Time) AutotransferQuerySet {
	return qs.w(qs.db.Where("updated_at >= ?", updatedAt))
}

// UpdatedAtLt is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) UpdatedAtLt(updatedAt time.Time) AutotransferQuerySet {
	return qs.w(qs.db.Where("updated_at < ?", updatedAt))
}

// UpdatedAtLte is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) UpdatedAtLte(updatedAt time.Time) AutotransferQuerySet {
	return qs.w(qs.db.Where("updated_at <= ?", updatedAt))
}

// UpdatedAtNe is an autogenerated method
// nolint: dupl
func (qs AutotransferQuerySet) UpdatedAtNe(updatedAt time.Time) AutotransferQuerySet {
	return qs.w(qs.db.Where("updated_at != ?", updatedAt))
}

// ===== END of query set AutotransferQuerySet

// ===== BEGIN of Autotransfer modifiers

type autotransferDBSchemaField string

func (f autotransferDBSchemaField) String() string {
	return string(f)
}

// AutotransferDBSchema stores db field names of Autotransfer
var AutotransferDBSchema = struct {
	ID          autotransferDBSchemaField
	CreatedAt   autotransferDBSchemaField
	UpdatedAt   autotransferDBSchemaField
	DeletedAt   autotransferDBSchemaField
	SourceTxnID autotransferDBSchemaField
	TargetTxnID autotransferDBSchemaField
	SourceID    autotransferDBSchemaField
	SourceType  autotransferDBSchemaField
	TargetType  autotransferDBSchemaField
	TargetID    autotransferDBSchemaField
	Amount      autotransferDBSchemaField
}{

	ID:          autotransferDBSchemaField("id"),
	CreatedAt:   autotransferDBSchemaField("created_at"),
	UpdatedAt:   autotransferDBSchemaField("updated_at"),
	DeletedAt:   autotransferDBSchemaField("deleted_at"),
	SourceTxnID: autotransferDBSchemaField("source_txn_id"),
	TargetTxnID: autotransferDBSchemaField("target_txn_id"),
	SourceID:    autotransferDBSchemaField("source_id"),
	SourceType:  autotransferDBSchemaField("source_type"),
	TargetType:  autotransferDBSchemaField("target_type"),
	TargetID:    autotransferDBSchemaField("target_id"),
	Amount:      autotransferDBSchemaField("amount"),
}

// Update updates Autotransfer fields by primary key
func (o *Autotransfer) Update(db *gorm.DB, fields ...autotransferDBSchemaField) error {
	dbNameToFieldName := map[string]interface{}{
		"id":            o.ID,
		"created_at":    o.CreatedAt,
		"updated_at":    o.UpdatedAt,
		"deleted_at":    o.DeletedAt,
		"source_txn_id": o.SourceTxnID,
		"target_txn_id": o.TargetTxnID,
		"source_id":     o.SourceID,
		"source_type":   o.SourceType,
		"target_type":   o.TargetType,
		"target_id":     o.TargetID,
		"amount":        o.Amount,
	}
	u := map[string]interface{}{}
	for _, f := range fields {
		fs := f.String()
		u[fs] = dbNameToFieldName[fs]
	}
	if err := db.Model(o).Updates(u).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return err
		}

		return fmt.Errorf("can't update Autotransfer %v fields %v: %s",
			o, fields, err)
	}

	return nil
}

// AutotransferUpdater is an Autotransfer updates manager
type AutotransferUpdater struct {
	fields map[string]interface{}
	db     *gorm.DB
}

// NewAutotransferUpdater creates new Autotransfer updater
func NewAutotransferUpdater(db *gorm.DB) AutotransferUpdater {
	return AutotransferUpdater{
		fields: map[string]interface{}{},
		db:     db.Model(&Autotransfer{}),
	}
}

// ===== END of Autotransfer modifiers

// ===== END of all query sets
